# Generated by Django 6.0.4 on 2026-04-18 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialty', models.CharField(choices=[('fitness', 'Fitness'), ('bodybuilding', 'Bodybuilding'), ('weight_loss', 'Weight Loss'), ('crossfit', 'CrossFit'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('nutrition', 'Nutrition'), ('other', 'Other')], default='fitness', max_length=50)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('price_per_session', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/photos/')),
                ('available_online', models.BooleanField(default=False)),
                ('available_in_person', models.BooleanField(default=True)),
                ('instagram', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__full_name'],
            },
        ),
    ]
