# Generated by Django 6.0.4 on 2026-04-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coaches/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='coaches.coachprofile')),
            ],
            options={
                'verbose_name': 'Coach gallery image',
                'verbose_name_plural': 'Coach gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
