# Generated by Django 6.0.4 on 2026-04-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coachgalleryimage'),
        ('gyms', '0004_gymgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='gyms.gym'),
        ),
    ]
