# Generated by Django 6.0.4 on 2026-07-21 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0003_coachprofile_gym"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coachprofile",
            options={
                "ordering": ["user__full_name"],
                "verbose_name": "Coach profile",
                "verbose_name_plural": "Coach profiles",
            },
        ),
        migrations.CreateModel(
            name="CoachTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("rw", "Kinyarwanda")],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="coaches.coachprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach translation",
                "verbose_name_plural": "Coach translations",
                "ordering": ("coach", "language"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("coach", "language"),
                        name="unique_coach_translation_language",
                    )
                ],
            },
        ),
    ]
