# Generated by Django 6.0.4 on 2026-07-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0004_alter_coachprofile_options_coachtranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachprofile",
            name="bio",
        ),
    ]
