# Generated by Django 6.0.4 on 2026-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('training', 'Training'), ('nutrition', 'Nutrition'), ('weight-loss', 'Weight Loss'), ('muscle-gain', 'Muscle Gain'), ('gym-tips', 'Gym Tips'), ('wellness', 'Wellness')], default='training', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
