# Generated by Django 6.0.4 on 2026-07-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.RemoveField(
            model_name="article",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title",
        ),
        migrations.AlterField(
            model_name="article",
            name="author_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("nutrition", "Nutrition"),
                    ("weight-loss", "Weight Loss"),
                    ("muscle-gain", "Muscle Gain"),
                    ("gym-tips", "Gym Tips"),
                    ("wellness", "Wellness"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ArticleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("rw", "Kinyarwanda")], max_length=5
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "language"),
                        name="unique_article_translation_language",
                    ),
                    models.UniqueConstraint(
                        fields=("language", "slug"),
                        name="unique_article_slug_per_language",
                    ),
                ],
            },
        ),
    ]
