# Generated by Django 6.0.4 on 2026-07-19 14:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_options_remove_article_content_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="articletranslation",
            name="unique_article_slug_per_language",
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="excerpt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("rw", "Kinyarwanda")], max_length=2
            ),
        ),
    ]
