# Generated by Django 6.0.4 on 2026-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0003_remove_articletranslation_unique_article_slug_per_language_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("nutrition", "Nutrition"),
                    ("weight-loss", "Weight Loss"),
                    ("muscle-gain", "Muscle Gain"),
                    ("gym-tips", "Gym Tips"),
                    ("wellness", "Wellness"),
                    ("news", "News"),
                ],
                max_length=50,
            ),
        ),
    ]
