# Generated by Django 6.0.4 on 2026-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_facebook_gym_instagram_gym_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
