# Generated by Django 6.0.4 on 2026-07-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0004_gymgalleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("rw", "Kinyarwanda")], max_length=2
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=255)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gyms.gym",
                    ),
                ),
            ],
            options={
                "unique_together": {("gym", "language")},
            },
        ),
    ]
