# Generated by Django 6.0.4 on 2026-07-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0005_gymtranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gym",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gym",
            name="opening_hours",
        ),
    ]
