# Generated by Django 6.0.4 on 2026-07-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0006_remove_gym_description_remove_gym_opening_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gymtranslation",
            options={
                "ordering": ("gym", "language"),
                "verbose_name": "Gym translation",
                "verbose_name_plural": "Gym translations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="gymtranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="gymtranslation",
            constraint=models.UniqueConstraint(
                fields=("gym", "language"), name="unique_gym_translation_language"
            ),
        ),
    ]
