# Generated by Django 6.0.4 on 2026-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
