# Generated by Django 6.0.4 on 2026-08-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "articles",
            "0003_remove_articletranslation_unique_article_slug_per_language_and_more",
        ),
        ("coaches", "0005_remove_coachprofile_bio"),
        ("gyms", "0007_alter_gymtranslation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("rw", "Kinyarwanda"),
                            ("all", "All languages"),
                        ],
                        default="all",
                        help_text="Language spoken in the video.",
                        max_length=3,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbnails/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="articles.article",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="coaches.coachprofile",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="gyms.gym",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("rw", "Kinyarwanda")], max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "language"),
                        name="unique_video_translation_language",
                    ),
                    models.UniqueConstraint(
                        fields=("language", "slug"),
                        name="unique_video_translation_language_slug",
                    ),
                ],
            },
        ),
    ]
